### ISSUE TITLE
Not working on Alfred v3.8 and MacOS 10.14

### ISSUE THREAD

**Issue by b-d-m-p** [fabiospampinato/alfred-spaces-workflow#1] opened 2019-02-20 07:41 UTC
Like the title says.

**Comment by fabiospampinato** [comment] 2019-02-20 16:48
It's working for me and I'm using the same version of the OS and Alfred. I need more details 🤷‍♂️.

**Comment by fabiospampinato** [comment] 2019-08-10 22:04
I can now reproduce this, but only because I upgraded to Alfred v4. Fix coming soon!

**Comment by fabiospampinato** [comment] 2019-08-10 22:18
I've fixed the issue for Alfred v4. 

@b-d-m-p your issue must be originating from something else, I can't reproduce it right now, so I'm closing this. If anybody has any clue on how I can reproduce this reliably I'll be happy to reopen this issue again.

**Closed as completed by fabiospampinato** 2019-08-10 22:18 UTC
Labels: needs more info
